#!/bin/bash

NAME="{{ project_name }}"
DIR=/home/{{ USER_NAME }}/{{ ROOT_NAME }}
USER={{ USER_NAME }}
GROUP={{ USER_NAME }}
WORKERS=3
BIND=unix:/home/{{ USER_NAME }}/run/gunicorn.sock
DJANGO_SETTINGS_MODULE={{ project_name }}.settings.production
DJANGO_WSGI_MODULE={{ project_name }}.wsgi
LOG_LEVEL=error

cd $DIR
source ../bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
